<?php

/**
 * @file
 * Contains monetdb_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Fetches the local NID from the migration source destination mapping table.
 */
function _vtvmi_migrate_get_local_nid($nid) {
    $result = \Drupal::database()->select('migrate_map_vtvmi_books', 'mmvb')
        ->fields('mmvb', array('destid1'))
        ->condition('mmvb.sourceid1', $nid)
        ->execute()->fetchField();
    if ($result) {
        return $result;
    }
}